x-app-build: &app-build
  context: ../..
  dockerfile: infra/compose/Dockerfile

name: ord

volumes:
  node_data: {}

networks:
  ord: {}

services:
  init-perms:
    image: alpine:3.20
    command: ['/bin/sh', '-lc', 'mkdir -p /data && chown -R 1001:1001 /data']
    volumes:
      - ${HOST_DATA_DIR:-./data}:/data
    restart: 'no'
    networks:
      - ord
  node:
    profiles: [local-node]
    image: ghcr.io/autonomys/node:${NODE_DOCKER_TAG}
    ports:
      - '30333:30333/tcp'
      - '30433:30433/tcp'
      - '30334:30334/tcp'
      - '127.0.0.1:9944:9944/tcp'
      - '127.0.0.1:8944:8944/tcp'
    restart: unless-stopped
    volumes:
      - node_data:/var/subspace:rw
    command:
      [
        'run',
        '--chain',
        '${NETWORK_ID:-mainnet}',
        '--base-path',
        '/var/subspace',
        '--',
        '--domain-id',
        '${DOMAIN_ID:-0}',
        '--rpc-cors',
        'all',
        '--rpc-methods',
        'safe',
        '--rpc-listen-on',
        '0.0.0.0:8944',
      ]
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -H ''Content-Type: application/json'' -d ''{"id":1, "jsonrpc":"2.0", "method": "system_health", "params":[]}'' http://localhost:9944/',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - ord

  scheduler:
    build: *app-build
    image: ord-app:latest
    command: ['sh', '-lc', 'node dist/index.js']
    env_file:
      - ./.env
    environment:
      SCHEDULER_HOST: 0.0.0.0
      LOG_FILE_PATH: /data/logs/${SCHEDULER_LOG_FILE:-ord-scheduler.log}
    restart: unless-stopped
    depends_on:
      init-perms:
        condition: service_completed_successfully
    healthcheck:
      test: ['CMD', 'curl', '-sf', 'http://127.0.0.1:${SCHEDULER_PORT}/']
      interval: 10s
      timeout: 3s
      retries: 6
    volumes:
      - ${HOST_DATA_DIR:-./data}:/data
    networks:
      - ord

  api:
    build: *app-build
    image: ord-app:latest
    command: ['sh', '-lc', 'node dist/server/app.js']
    env_file:
      - ./.env
    environment:
      SCHEDULER_HEALTH_URL: http://scheduler:${SCHEDULER_PORT:-3000}/
      SERVER_HOST: 0.0.0.0
      LOG_FILE_PATH: /data/logs/${API_LOG_FILE:-ord-api.log}
    restart: unless-stopped
    depends_on:
      init-perms:
        condition: service_completed_successfully
      scheduler:
        condition: service_started
    healthcheck:
      test: ['CMD', 'curl', '-sf', 'http://127.0.0.1:${SERVER_PORT:-3001}/health']
      interval: 10s
      timeout: 3s
      retries: 6
    volumes:
      - ${HOST_DATA_DIR:-./data}:/data
    networks:
      - ord

  proxy:
    image: nginx:1.27-alpine
    depends_on:
      - api
    env_file:
      - ./.env
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
    ports:
      - '${PROXY_HOST_PORT:-80}:80'
    restart: unless-stopped
    networks:
      - ord
